### PR TITLE
fix: Permission Denied when deploying using Dockerfile

### PR DESCRIPTION
**Pull request by Ian729**

### CODE REVIEW

**Comment by Ian729** [comment]
Hit permission denied when running docker.
Following the guidance listed [here](https://github.com/shfshanyue/wechat-chatgpt/issues/4) to delete the USER line

**Comment by shfshanyue** [comment]
Try to re-clone in a new folder directory？

**Comment by Ian729** [comment]
I don't quite get what you mean. I solved the issue by applying the change.

**Comment by 1328449337** [comment]
您好～邮件我已收到，我将尽快查阅。

**Pull request merged**
